### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by RinatValiullov** [sinedied/ng-lite-starter#1]
The link to the dev.to article is broken.

> See this [dev.to article](https://github.com/sinedied/ng-lite-starter/blob/main/WIP) to see how this starter was created and for more details about the differences with Angular CLI's default ng new.

**Comment by sinedied** [comment]
Thanks for your interest! That's become the article hasn't been published yet, I'm still working on it 🙂

**Comment by RinatValiullov** [comment]
Oh. I see. In that case, sorry for being so hasty. I close the issue.
